# Generated by Django 5.2.9 on 2025-12-06 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='approvalrule',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='consumptionhistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Consumption Histories'},
        ),
        migrations.AlterModelOptions(
            name='consumptionpattern',
            options={'ordering': ['-confidence_score']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['predicted_runout_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendorproduct',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ORDER', 'Place Order'), ('PREDICT', 'Make Prediction'), ('SYNC', 'Sync with Vendor'), ('CONSUME', 'Consume Item')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='vendor_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendorproduct'),
        ),
        migrations.AlterField(
            model_name='consumptionhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consumptionhistory',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('RECEIPT', 'Receipt OCR'), ('API', 'Smart Appliance API'), ('PREDICTION', 'ML Prediction')], default='MANUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='core_approv_status_044e10_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_at'], name='core_approv_request_65931b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product'], name='core_invent_product_d3a388_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['expiry_date'], name='core_invent_expiry__98cc49_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['predicted_runout_date'], name='core_predic_predict_e04cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', 'is_active'], name='core_predic_user_id_353884_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_784c92_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'status'], name='core_shoppi_user_id_16c2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['created_at'], name='core_shoppi_created_f56d9a_idx'),
        ),
    ]
